name: cs_beldex_flutter_libs
description: "Binaries required to use cs_beldex in a Flutter project"
version: 1.0.0
repository: https://github.com/MogamboPuri/cs_beldex
homepage: https://github.com/MogamboPuri/cs_beldex
issue_tracker: https://github.com/MogamboPuri/cs_beldex/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  cs_beldex_flutter_libs_platform_interface: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_platform_interface
  cs_beldex_flutter_libs_android: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_android
  cs_beldex_flutter_libs_ios: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_ios
  cs_beldex_flutter_libs_linux: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_linux
  cs_beldex_flutter_libs_macos: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_macos
  cs_beldex_flutter_libs_windows: 
    git:
      url: https://github.com/MogamboPuri/cs_beldex.git
      path: cs_beldex_flutter_libs_windows

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cs_beldex_flutter_libs_android
      ios:
        default_package: cs_beldex_flutter_libs_ios
      linux:
        default_package: cs_beldex_flutter_libs_linux
      macos:
        default_package: cs_beldex_flutter_libs_macos
      windows:
        default_package: cs_beldex_flutter_libs_windows