name: cs_beldex_flutter_libs
description: "Binaries required to use cs_beldex in a Flutter project"
version: 2.0.1
repository: https://github.com/MogamboPuri/cs_beldex
homepage: https://github.com/MogamboPuri/cs_beldex
issue_tracker: https://github.com/MogamboPuri/cs_beldex/issues

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  cs_beldex_flutter_libs_platform_interface: 1.0.0
  cs_beldex_flutter_libs_android: 1.1.1
  cs_beldex_flutter_libs_linux: 1.3.0
  cs_beldex_flutter_libs_windows: 1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: cs_beldex_flutter_libs_android
      linux:
        default_package: cs_beldex_flutter_libs_linux
      windows:
        default_package: cs_beldex_flutter_libs_windows
