name: example_app
description: "A cs_beldex Flutter example app"
repository: https://github.com/MogamboPuri/cs_beldex
homepage: https://github.com/MogamboPuri/cs_beldex
issue_tracker: https://github.com/MogamboPuri/cs_beldex/issues
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  cs_beldex:
    path: ../cs_beldex
  cs_beldex_flutter_libs:
    path: ../cs_beldex_flutter_libs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
